name: Keep n8n & Supabase Awake

on:
  schedule:
    - cron: "*/9 * * * *"  # every 9 minutes
  workflow_dispatch:        # allows manual run

jobs:
  ping_n8n:
    name: Ping n8n (Render)
    runs-on: ubuntu-latest
    steps:
      - name: Ping n8n Render Service
        run: |
          echo "[$(date)] Starting n8n keep-alive ping..."
          sleep $((RANDOM % 240))   # random delay up to 4 minutes
          curl -fsS https://n8n-chat-4jit.onrender.com/healthz \
            || echo "n8n ping failed"

  ping_supabase:
    name: Ping Supabase
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase REST API
        env:
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          echo "[$(date)] Starting Supabase keep-alive ping..."
          sleep $((RANDOM % 240))   # random delay up to 4 minutes
          curl -fsS \
            -H "apikey: $SUPABASE_ANON_KEY" \
            -H "Authorization: Bearer $SUPABASE_ANON_KEY" \
            "https://sxzmmwetnukosqfqhbdo.supabase.co/rest/v1/user?limit=1" \
            || echo "Supabase ping failed"
