name: Keep n8n & Supabase Awake

on:
  schedule:
    - cron: "*/9 * * * *"  # every 9 minutes
  workflow_dispatch:        # allows manual run

jobs:
  ping_n8n:
    name: Ping n8n (Render)
    runs-on: ubuntu-latest
    steps:
      - name: Ping n8n Render Service
        run: |
          echo "[$(date)] Starting n8n keep-alive ping..."
          sleep $((RANDOM % 240))   # random delay up to 4 minutes
          curl -fsS https://n8n-chat-4jit.onrender.com/healthz \
            || echo "n8n ping failed"

  ping_supabase:
    name: Ping Supabase
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase API
        run: |
          echo "[$(date)] Starting Supabase keep-alive ping..."
          sleep $((RANDOM % 240))   # random delay up to 4 minutes
          curl -fsS "https://aws-1-ap-southeast-1.pooler.supabase.com:6543"
            || echo "Supabase ping failed"
            
