name: n8n keep-alive

on:
  schedule:
    - cron: "*/9 * * * *"  # every 9 min
  workflow_dispatch:        # <-- enables the “Run workflow” button manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Starting keep-alive ping..."
          sleep $((RANDOM % 240))   # random delay up to 4 min
          curl -fsS https://n8n-chat-4jit.onrender.com/healthz
